### ISSUE TITLE
I want to see the results of the dungeon output. ダンジョンの出力結果が欲しいです

### ISSUE THREAD

**Issue by AsPJT** [pprobst/roguelike#1]
I want to see the results of the dungeon output.

ローグライクダンジョンの出力結果が欲しいです。
どういった形のダンジョンが生成されるのか、画像などで見たいです。
もしよろしければお手数ですが、READMEに出力結果を添付して頂けると幸いです。

**Comment by pprobst** [comment]
Sure, no problem. 

I've added some 80x60 outputs [here](https://github.com/pprobst/roguelike/tree/main/dungeon-outputs). They're not very organized, as they are originally part of my bachelor thesis, but I hope they're still understandable. To help with comprehension I've written a small README with some necessary explanations for things that may not be obvious at first glance, as some results are part of some experiments that are only documented in [Portuguese](https://github.com/pprobst/tcc-ufsm-2020/blob/master/monografia.pdf).

Just keep in mind that this repository is a work in progress. I'll -- albeit slowly --, fix and add things eventually. The map generation system I've implemented for the game is honestly quite bad at the moment, at least for industry standards (even if "it works" for the most part).
